/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EvaluationSubmittedRouteImport } from './routes/evaluation-submitted'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as EvaluationCycleTokenRouteImport } from './routes/evaluation.$cycleToken'
import { Route as AuthenticatedAccountPasswordRouteImport } from './routes/_authenticated/account.password'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin.audit-logs'
import { Route as AuthenticatedAdminEmployeeProfilesRouteImport } from './routes/_authenticated/admin.employee-profiles'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedHrIndexRouteImport } from './routes/_authenticated/hr.index'
import { Route as AuthenticatedPresidentIndexRouteImport } from './routes/_authenticated/president.index'
import { Route as AuthenticatedPresidentEmployeesRouteImport } from './routes/_authenticated/president.employees'
import { Route as AuthenticatedSupervisorIndexRouteImport } from './routes/_authenticated/supervisor.index'
import { Route as AuthenticatedHrCyclesIndexRouteImport } from './routes/_authenticated/hr.cycles.index'
import { Route as AuthenticatedHrCyclesCycleIdRouteImport } from './routes/_authenticated/hr.cycles.$cycleId'
import { Route as AuthenticatedHrEvaluationHistoryIndexRouteImport } from './routes/_authenticated/hr.evaluation-history.index'
import { Route as AuthenticatedHrEvaluationHistoryEvaluationIdRouteImport } from './routes/_authenticated/hr.evaluation-history.$evaluationId'
import { Route as AuthenticatedPresidentEvaluationsIndexRouteImport } from './routes/_authenticated/president.evaluations.index'
import { Route as AuthenticatedPresidentEvaluationsEvaluationIdRouteImport } from './routes/_authenticated/president.evaluations.$evaluationId'
import { Route as AuthenticatedSupervisorEvaluationsIndexRouteImport } from './routes/_authenticated/supervisor.evaluations.index'
import { Route as AuthenticatedSupervisorEvaluationsEvaluationIdRouteImport } from './routes/_authenticated/supervisor.evaluations.$evaluationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationSubmittedRoute = EvaluationSubmittedRouteImport.update({
  id: '/evaluation-submitted',
  path: '/evaluation-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationCycleTokenRoute = EvaluationCycleTokenRouteImport.update({
  id: '/evaluation/$cycleToken',
  path: '/evaluation/$cycleToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountPasswordRoute =
  AuthenticatedAccountPasswordRouteImport.update({
    id: '/account/password',
    path: '/account/password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/admin/audit-logs',
    path: '/admin/audit-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployeeProfilesRoute =
  AuthenticatedAdminEmployeeProfilesRouteImport.update({
    id: '/admin/employee-profiles',
    path: '/admin/employee-profiles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/admin/employees',
    path: '/admin/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrIndexRoute = AuthenticatedHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresidentIndexRoute =
  AuthenticatedPresidentIndexRouteImport.update({
    id: '/president/',
    path: '/president/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPresidentEmployeesRoute =
  AuthenticatedPresidentEmployeesRouteImport.update({
    id: '/president/employees',
    path: '/president/employees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorIndexRoute =
  AuthenticatedSupervisorIndexRouteImport.update({
    id: '/supervisor/',
    path: '/supervisor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrCyclesIndexRoute =
  AuthenticatedHrCyclesIndexRouteImport.update({
    id: '/hr/cycles/',
    path: '/hr/cycles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrCyclesCycleIdRoute =
  AuthenticatedHrCyclesCycleIdRouteImport.update({
    id: '/hr/cycles/$cycleId',
    path: '/hr/cycles/$cycleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrEvaluationHistoryIndexRoute =
  AuthenticatedHrEvaluationHistoryIndexRouteImport.update({
    id: '/hr/evaluation-history/',
    path: '/hr/evaluation-history/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrEvaluationHistoryEvaluationIdRoute =
  AuthenticatedHrEvaluationHistoryEvaluationIdRouteImport.update({
    id: '/hr/evaluation-history/$evaluationId',
    path: '/hr/evaluation-history/$evaluationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPresidentEvaluationsIndexRoute =
  AuthenticatedPresidentEvaluationsIndexRouteImport.update({
    id: '/president/evaluations/',
    path: '/president/evaluations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPresidentEvaluationsEvaluationIdRoute =
  AuthenticatedPresidentEvaluationsEvaluationIdRouteImport.update({
    id: '/president/evaluations/$evaluationId',
    path: '/president/evaluations/$evaluationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorEvaluationsIndexRoute =
  AuthenticatedSupervisorEvaluationsIndexRouteImport.update({
    id: '/supervisor/evaluations/',
    path: '/supervisor/evaluations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupervisorEvaluationsEvaluationIdRoute =
  AuthenticatedSupervisorEvaluationsEvaluationIdRouteImport.update({
    id: '/supervisor/evaluations/$evaluationId',
    path: '/supervisor/evaluations/$evaluationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluation-submitted': typeof EvaluationSubmittedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/evaluation/$cycleToken': typeof EvaluationCycleTokenRoute
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/employee-profiles': typeof AuthenticatedAdminEmployeeProfilesRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/president/employees': typeof AuthenticatedPresidentEmployeesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/hr/': typeof AuthenticatedHrIndexRoute
  '/president/': typeof AuthenticatedPresidentIndexRoute
  '/supervisor/': typeof AuthenticatedSupervisorIndexRoute
  '/hr/cycles/$cycleId': typeof AuthenticatedHrCyclesCycleIdRoute
  '/hr/evaluation-history/$evaluationId': typeof AuthenticatedHrEvaluationHistoryEvaluationIdRoute
  '/president/evaluations/$evaluationId': typeof AuthenticatedPresidentEvaluationsEvaluationIdRoute
  '/supervisor/evaluations/$evaluationId': typeof AuthenticatedSupervisorEvaluationsEvaluationIdRoute
  '/hr/cycles/': typeof AuthenticatedHrCyclesIndexRoute
  '/hr/evaluation-history/': typeof AuthenticatedHrEvaluationHistoryIndexRoute
  '/president/evaluations/': typeof AuthenticatedPresidentEvaluationsIndexRoute
  '/supervisor/evaluations/': typeof AuthenticatedSupervisorEvaluationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluation-submitted': typeof EvaluationSubmittedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/evaluation/$cycleToken': typeof EvaluationCycleTokenRoute
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/employee-profiles': typeof AuthenticatedAdminEmployeeProfilesRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/president/employees': typeof AuthenticatedPresidentEmployeesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/hr': typeof AuthenticatedHrIndexRoute
  '/president': typeof AuthenticatedPresidentIndexRoute
  '/supervisor': typeof AuthenticatedSupervisorIndexRoute
  '/hr/cycles/$cycleId': typeof AuthenticatedHrCyclesCycleIdRoute
  '/hr/evaluation-history/$evaluationId': typeof AuthenticatedHrEvaluationHistoryEvaluationIdRoute
  '/president/evaluations/$evaluationId': typeof AuthenticatedPresidentEvaluationsEvaluationIdRoute
  '/supervisor/evaluations/$evaluationId': typeof AuthenticatedSupervisorEvaluationsEvaluationIdRoute
  '/hr/cycles': typeof AuthenticatedHrCyclesIndexRoute
  '/hr/evaluation-history': typeof AuthenticatedHrEvaluationHistoryIndexRoute
  '/president/evaluations': typeof AuthenticatedPresidentEvaluationsIndexRoute
  '/supervisor/evaluations': typeof AuthenticatedSupervisorEvaluationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/evaluation-submitted': typeof EvaluationSubmittedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/evaluation/$cycleToken': typeof EvaluationCycleTokenRoute
  '/_authenticated/account/password': typeof AuthenticatedAccountPasswordRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/employee-profiles': typeof AuthenticatedAdminEmployeeProfilesRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/president/employees': typeof AuthenticatedPresidentEmployeesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/hr/': typeof AuthenticatedHrIndexRoute
  '/_authenticated/president/': typeof AuthenticatedPresidentIndexRoute
  '/_authenticated/supervisor/': typeof AuthenticatedSupervisorIndexRoute
  '/_authenticated/hr/cycles/$cycleId': typeof AuthenticatedHrCyclesCycleIdRoute
  '/_authenticated/hr/evaluation-history/$evaluationId': typeof AuthenticatedHrEvaluationHistoryEvaluationIdRoute
  '/_authenticated/president/evaluations/$evaluationId': typeof AuthenticatedPresidentEvaluationsEvaluationIdRoute
  '/_authenticated/supervisor/evaluations/$evaluationId': typeof AuthenticatedSupervisorEvaluationsEvaluationIdRoute
  '/_authenticated/hr/cycles/': typeof AuthenticatedHrCyclesIndexRoute
  '/_authenticated/hr/evaluation-history/': typeof AuthenticatedHrEvaluationHistoryIndexRoute
  '/_authenticated/president/evaluations/': typeof AuthenticatedPresidentEvaluationsIndexRoute
  '/_authenticated/supervisor/evaluations/': typeof AuthenticatedSupervisorEvaluationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evaluation-submitted'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/unauthorized'
    | '/evaluation/$cycleToken'
    | '/account/password'
    | '/admin/audit-logs'
    | '/admin/employee-profiles'
    | '/admin/employees'
    | '/admin/roles'
    | '/admin/users'
    | '/president/employees'
    | '/admin/'
    | '/hr/'
    | '/president/'
    | '/supervisor/'
    | '/hr/cycles/$cycleId'
    | '/hr/evaluation-history/$evaluationId'
    | '/president/evaluations/$evaluationId'
    | '/supervisor/evaluations/$evaluationId'
    | '/hr/cycles/'
    | '/hr/evaluation-history/'
    | '/president/evaluations/'
    | '/supervisor/evaluations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evaluation-submitted'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/unauthorized'
    | '/evaluation/$cycleToken'
    | '/account/password'
    | '/admin/audit-logs'
    | '/admin/employee-profiles'
    | '/admin/employees'
    | '/admin/roles'
    | '/admin/users'
    | '/president/employees'
    | '/admin'
    | '/hr'
    | '/president'
    | '/supervisor'
    | '/hr/cycles/$cycleId'
    | '/hr/evaluation-history/$evaluationId'
    | '/president/evaluations/$evaluationId'
    | '/supervisor/evaluations/$evaluationId'
    | '/hr/cycles'
    | '/hr/evaluation-history'
    | '/president/evaluations'
    | '/supervisor/evaluations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/evaluation-submitted'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/unauthorized'
    | '/evaluation/$cycleToken'
    | '/_authenticated/account/password'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/employee-profiles'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/users'
    | '/_authenticated/president/employees'
    | '/_authenticated/admin/'
    | '/_authenticated/hr/'
    | '/_authenticated/president/'
    | '/_authenticated/supervisor/'
    | '/_authenticated/hr/cycles/$cycleId'
    | '/_authenticated/hr/evaluation-history/$evaluationId'
    | '/_authenticated/president/evaluations/$evaluationId'
    | '/_authenticated/supervisor/evaluations/$evaluationId'
    | '/_authenticated/hr/cycles/'
    | '/_authenticated/hr/evaluation-history/'
    | '/_authenticated/president/evaluations/'
    | '/_authenticated/supervisor/evaluations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EvaluationSubmittedRoute: typeof EvaluationSubmittedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  EvaluationCycleTokenRoute: typeof EvaluationCycleTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation-submitted': {
      id: '/evaluation-submitted'
      path: '/evaluation-submitted'
      fullPath: '/evaluation-submitted'
      preLoaderRoute: typeof EvaluationSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/$cycleToken': {
      id: '/evaluation/$cycleToken'
      path: '/evaluation/$cycleToken'
      fullPath: '/evaluation/$cycleToken'
      preLoaderRoute: typeof EvaluationCycleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/password': {
      id: '/_authenticated/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AuthenticatedAccountPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employee-profiles': {
      id: '/_authenticated/admin/employee-profiles'
      path: '/admin/employee-profiles'
      fullPath: '/admin/employee-profiles'
      preLoaderRoute: typeof AuthenticatedAdminEmployeeProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/': {
      id: '/_authenticated/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof AuthenticatedHrIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/president/': {
      id: '/_authenticated/president/'
      path: '/president'
      fullPath: '/president/'
      preLoaderRoute: typeof AuthenticatedPresidentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/president/employees': {
      id: '/_authenticated/president/employees'
      path: '/president/employees'
      fullPath: '/president/employees'
      preLoaderRoute: typeof AuthenticatedPresidentEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/': {
      id: '/_authenticated/supervisor/'
      path: '/supervisor'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof AuthenticatedSupervisorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/cycles/': {
      id: '/_authenticated/hr/cycles/'
      path: '/hr/cycles'
      fullPath: '/hr/cycles/'
      preLoaderRoute: typeof AuthenticatedHrCyclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/cycles/$cycleId': {
      id: '/_authenticated/hr/cycles/$cycleId'
      path: '/hr/cycles/$cycleId'
      fullPath: '/hr/cycles/$cycleId'
      preLoaderRoute: typeof AuthenticatedHrCyclesCycleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/evaluation-history/': {
      id: '/_authenticated/hr/evaluation-history/'
      path: '/hr/evaluation-history'
      fullPath: '/hr/evaluation-history/'
      preLoaderRoute: typeof AuthenticatedHrEvaluationHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/evaluation-history/$evaluationId': {
      id: '/_authenticated/hr/evaluation-history/$evaluationId'
      path: '/hr/evaluation-history/$evaluationId'
      fullPath: '/hr/evaluation-history/$evaluationId'
      preLoaderRoute: typeof AuthenticatedHrEvaluationHistoryEvaluationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/president/evaluations/': {
      id: '/_authenticated/president/evaluations/'
      path: '/president/evaluations'
      fullPath: '/president/evaluations/'
      preLoaderRoute: typeof AuthenticatedPresidentEvaluationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/president/evaluations/$evaluationId': {
      id: '/_authenticated/president/evaluations/$evaluationId'
      path: '/president/evaluations/$evaluationId'
      fullPath: '/president/evaluations/$evaluationId'
      preLoaderRoute: typeof AuthenticatedPresidentEvaluationsEvaluationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/evaluations/': {
      id: '/_authenticated/supervisor/evaluations/'
      path: '/supervisor/evaluations'
      fullPath: '/supervisor/evaluations/'
      preLoaderRoute: typeof AuthenticatedSupervisorEvaluationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/evaluations/$evaluationId': {
      id: '/_authenticated/supervisor/evaluations/$evaluationId'
      path: '/supervisor/evaluations/$evaluationId'
      fullPath: '/supervisor/evaluations/$evaluationId'
      preLoaderRoute: typeof AuthenticatedSupervisorEvaluationsEvaluationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountPasswordRoute: typeof AuthenticatedAccountPasswordRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminEmployeeProfilesRoute: typeof AuthenticatedAdminEmployeeProfilesRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedPresidentEmployeesRoute: typeof AuthenticatedPresidentEmployeesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedHrIndexRoute: typeof AuthenticatedHrIndexRoute
  AuthenticatedPresidentIndexRoute: typeof AuthenticatedPresidentIndexRoute
  AuthenticatedSupervisorIndexRoute: typeof AuthenticatedSupervisorIndexRoute
  AuthenticatedHrCyclesCycleIdRoute: typeof AuthenticatedHrCyclesCycleIdRoute
  AuthenticatedHrEvaluationHistoryEvaluationIdRoute: typeof AuthenticatedHrEvaluationHistoryEvaluationIdRoute
  AuthenticatedPresidentEvaluationsEvaluationIdRoute: typeof AuthenticatedPresidentEvaluationsEvaluationIdRoute
  AuthenticatedSupervisorEvaluationsEvaluationIdRoute: typeof AuthenticatedSupervisorEvaluationsEvaluationIdRoute
  AuthenticatedHrCyclesIndexRoute: typeof AuthenticatedHrCyclesIndexRoute
  AuthenticatedHrEvaluationHistoryIndexRoute: typeof AuthenticatedHrEvaluationHistoryIndexRoute
  AuthenticatedPresidentEvaluationsIndexRoute: typeof AuthenticatedPresidentEvaluationsIndexRoute
  AuthenticatedSupervisorEvaluationsIndexRoute: typeof AuthenticatedSupervisorEvaluationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountPasswordRoute: AuthenticatedAccountPasswordRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminEmployeeProfilesRoute:
    AuthenticatedAdminEmployeeProfilesRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedPresidentEmployeesRoute: AuthenticatedPresidentEmployeesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedHrIndexRoute: AuthenticatedHrIndexRoute,
  AuthenticatedPresidentIndexRoute: AuthenticatedPresidentIndexRoute,
  AuthenticatedSupervisorIndexRoute: AuthenticatedSupervisorIndexRoute,
  AuthenticatedHrCyclesCycleIdRoute: AuthenticatedHrCyclesCycleIdRoute,
  AuthenticatedHrEvaluationHistoryEvaluationIdRoute:
    AuthenticatedHrEvaluationHistoryEvaluationIdRoute,
  AuthenticatedPresidentEvaluationsEvaluationIdRoute:
    AuthenticatedPresidentEvaluationsEvaluationIdRoute,
  AuthenticatedSupervisorEvaluationsEvaluationIdRoute:
    AuthenticatedSupervisorEvaluationsEvaluationIdRoute,
  AuthenticatedHrCyclesIndexRoute: AuthenticatedHrCyclesIndexRoute,
  AuthenticatedHrEvaluationHistoryIndexRoute:
    AuthenticatedHrEvaluationHistoryIndexRoute,
  AuthenticatedPresidentEvaluationsIndexRoute:
    AuthenticatedPresidentEvaluationsIndexRoute,
  AuthenticatedSupervisorEvaluationsIndexRoute:
    AuthenticatedSupervisorEvaluationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EvaluationSubmittedRoute: EvaluationSubmittedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  EvaluationCycleTokenRoute: EvaluationCycleTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
