-- Phase 2: workflow enum values. Forward-only migration.
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'REVIEWING_SUPERVISOR';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'COMMITTEE';
ALTER TYPE public.evaluation_status ADD VALUE IF NOT EXISTS 'REVIEWING_SUPERVISOR_REVIEW';
ALTER TYPE public.evaluation_status ADD VALUE IF NOT EXISTS 'PERSONNEL_PROCESSING';
ALTER TYPE public.evaluation_status ADD VALUE IF NOT EXISTS 'COMMITTEE_REVIEW';
ALTER TYPE public.evaluation_status ADD VALUE IF NOT EXISTS 'PRESIDENT_APPROVAL';
ALTER TYPE public.evaluation_status ADD VALUE IF NOT EXISTS 'RESUBMITTED';
