// This file is automatically generated. Do not edit it directly.
import { createMiddleware, createServerOnlyFn } from "@tanstack/react-start";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const getCurrentRequest = createServerOnlyFn(async () => {
  const { getRequest } = await import("@tanstack/react-start/server");
  return getRequest();
});

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export async function authenticateSupabaseRequest() {
  const SUPABASE_URL = process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Configure the required Supabase environment variables.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const request = await getCurrentRequest();

  if (!request?.headers) {
    throw new Error("Unauthorized: No request headers available");
  }

  const authHeader = request.headers.get("authorization");

  if (!authHeader) {
    throw new Error("Unauthorized: No authorization header provided");
  }

  if (!authHeader.startsWith("Bearer ")) {
    throw new Error("Unauthorized: Only Bearer tokens are supported");
  }

  const token = authHeader.replace("Bearer ", "");
  if (!token) {
    throw new Error("Unauthorized: No token provided");
  }

  if (token.split(".").length !== 3) {
    throw new Error("Unauthorized: Invalid token");
  }

  const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });

  const { data, error } = await supabase.auth.getClaims(token);
  if (error || !data?.claims) {
    throw new Error("Unauthorized: Invalid token");
  }

  if (!data.claims.sub) {
    throw new Error("Unauthorized: No user ID found in token");
  }

  const { data: account, error: accountError } = await supabase
    .from("internal_users")
    .select("id, is_active, is_locked")
    .eq("id", data.claims.sub)
    .maybeSingle();
  if (accountError || !account || !account.is_active || account.is_locked) {
    throw new Error("Unauthorized: Account is inactive or locked");
  }

  return { supabase, userId: data.claims.sub, claims: data.claims };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const authenticated = await authenticateSupabaseRequest();
    const sessionId = String(authenticated.claims.session_id ?? "");
    if (!sessionId) throw new Error("Unauthorized: Session identity unavailable");
    const { isEmailOtpEnabled } = await import("@/lib/server-core.server");
    if (await isEmailOtpEnabled()) {
      const { supabaseAdmin } = await import("./client.server");
      const { data: verification } = await supabaseAdmin
        .from("email_mfa_challenges")
        .select("verified_at, expires_at")
        .eq("user_id", authenticated.userId)
        .eq("session_id", sessionId)
        .maybeSingle();
      if (!verification?.verified_at || new Date(verification.expires_at as string) < new Date()) {
        throw new Error("MFA_REQUIRED: Verify the code sent to your email");
      }
    }

    const { supabaseAdmin } = await import("./client.server");
    const { data: securitySession } = await supabaseAdmin
      .from("security_sessions" as never)
      .select("expires_at")
      .eq("user_id", authenticated.userId)
      .eq("session_id", sessionId)
      .maybeSingle();
    if (securitySession?.expires_at && new Date(String(securitySession.expires_at)) <= new Date()) {
      await supabaseAdmin
        .from("security_sessions" as never)
        .delete()
        .eq("user_id", authenticated.userId)
        .eq("session_id", sessionId);
      throw new Error("SESSION_EXPIRED: Sign in again to continue");
    }
    await supabaseAdmin.rpc(
      "touch_security_session" as never,
      {
        _user_id: authenticated.userId,
        _session_id: sessionId,
        _timeout_seconds: 180,
      } as never,
    );

    return next({
      context: {
        ...authenticated,
      },
    });
  },
);
